### ISSUE TITLE
Decoding error when running the app

### ISSUE THREAD

**Issue by mirkancal** [tryterra/Swift-Integration#2]
Hi there, thanks for the example package. When I run it, I'm getting this error down below, and the example app is stuck on a white screen.

`keyNotFound(CodingKeys(stringValue: "status", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"status\", intValue: nil) (\"status\").", underlyingError: nil))`

I've added dev_id and API key on Widget.swift, on  `widget.user_id =`, and `widget.TerraClient =` lines.

**Comment by JaafarRammal** [comment]
Hey @mirkancal,
The dev_id and API Key are used in both the widget file and the content view file. Did you replace in both?

In either case, my bad on the above, it wasn't apparent. I'll push some changes with a single config file that you have to fill instead of replacing bits in the ode

**Comment by mirkancal** [comment]
Thank you, now it works. Cool splash screen
